# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36894981cc38f844d0abfad39fac11db4b12a5d504ecf80d57e5f8a1ebf4beaffbc72c783f99379a9737fa84b3184f0b0968af4b10957100b459bce58c54d8cb

test:
  secret_key_base: b37be5c7b4dbb515cd4fa17480082313c7d99800fbf7d88af216c4dc3bbf0c151222455689250a7870c0287205a26a87edee1e2a7fb4dac6cc9f9a5f4a5e1a6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
